### basic 
GET http://localhost:3000/

### get all users
GET http://localhost:3000/users

### Login 
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "user1",
  "password": "user1"
}
